version: "3" # Composeファイルの書式のバージョン
services:
  nginx:
    image: nginx:latest # nginx:latestイメージを元にビルド
    ports:
      - 8080:80 # localhostの8080番ポートとdockerコンテナの80番ポートをバインド
    volumes:
      # ローカルのリソースをコンテナにマウント
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www/html:/var/www/html
    depends_on:
      - php # phpコンテナに依存

  php:
    build: ./php # php/Dockerfileを元にビルド
    volumes:
      - ./www/html:/var/www/html # www/htmlをコンテナの/var/www/htmlにマウント
    depends_on:
      - db # dbコンテナに依存

  db:
    image: mysql:5.7
    ports:
      - 3306:3306 # localhostの3306番ポートとdockerコンテナの3306番ポートをバインド
    volumes:
      - ./mysql/data:/var/lib/mysql # ./mysql/dataをコンテナの/var/lib/mysqlにマウント
    environment:
      MYSQL_ROOT_PASSWORD: secret